[7주차] 레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기
CodeSoom/week7-assignment-1 pull request #21
Opened 2020-11-02 15:06 UTC by juunini

- [ ] 로그인 컴포넌트 구현
- [ ] 로그인 컨테이너 구현
- [ ] 로그인 서비스 구현
- [ ] 로그인 액션, 리듀서 구현
- [ ] 로그인 페이지 구현
- [ ] 레스토랑 리뷰 컨테이너 구현
- [ ] 레스토랑 리뷰 서비스 구현
- [ ] 레스토랑 리뷰 액션, 리듀서 구현
- [ ] RestaurantPage에 레스토랑 리뷰 컨테이너 포함
- [ ] 로그인 시에만 레스토랑 리뷰 기능이 보이도록 처리
- [ ] [덤] 최신 리뷰가 가장 위에 표시되도록 정렬하기
- [ ] [덤] RestaurantPage에서 로그인이 안되어있다면 리뷰 폼이 disabled 되어있고
     로그인을 하면 리뷰를 남길 수 있다는 안내문구와 로그인 페이지로 가는 링크 추가

2020-11-03 14:53 UTC, Kihyun92 commented
폴더 구조부터 설계해보신 것 같아요! 좋습니다 👍  
라우팅이 들어가고 기능이 많아질수록 전체적인 구조를 어떻게 설계하는지도 중요해 질 것 같네요 :)

2020-11-04 14:58 UTC, Kihyun92 requested changes
TDD를 잘 가져가고 있고, 테스트를 꼼꼼하게 해주시는 것 같아요! 👍

2020-11-04 14:58 UTC, Kihyun92 commented on src/components/LoginForm.jsx
> +        disabled={!loginAble}
`form validation`하는 느낌으로 버튼을 disable 해보신것 같아요! 좋네요 👍 

하지만 `loginAble`이라는 변수명이 조금 어색한 것 같아요. camel case가 아닌 `~~able`과 같이 하나의 단어로 표현하는게 더 좋을 것 같아요.

아니면 `isValid` 같이 `검증된, 유효한`과 같은 느낌을 전달해줘도 좋을 것 같구요. 역시 변수명 선택이 가장 어렵네요..😅

2020-11-04 14:58 UTC, Kihyun92 commented on src/components/LoginForm.test.jsx
> +
```
beforeEach(() => {
    handleChangeId.mockClear();
    handleChangePassword.mockClear();
    handleClick.mockClear();
  });
```
각 테스트마다 영향을 끼칠 수 있기 때문에 `beforeEach`를 통해서 `mockClear`를 해주는건 어떨까요?

2020-11-04 14:58 UTC, Kihyun92 commented on src/components/LoginForm.test.jsx
> +      renderLogin({});
매번 빈 객체를 넣어주기보다, `renderLogin`을 선언할때 `default value`로 빈 객체를 넣어주는것도 좋을 것 같네요~

2020-11-04 14:58 UTC, Kihyun92 commented on src/containers/LoginContainer.test.jsx
> +      }));
dispatch 함수 mocking 해주는 부분이나 각 테스트마다 useDispatch, useSelector를 해주는 부분을 beforeEach를 통해서 각 테스트마다 독립적으로 실행되게 해주면 좋을 것 같아요~

2020-11-05 14:55 UTC, juunini commented on src/components/LoginForm.jsx
> +        disabled={!loginAble}
아... loginAble 다시 보니 좀 이상하긴 하네요 ㅎㅎ;
의도는 맞긴 한데 단어 선택이 이상했던 것 같습니다. 좀 더 생각해봐야겠네요 감사합니다

2020-11-05 14:56 UTC, juunini commented on src/components/LoginForm.test.jsx
> +
아, 그렇네요. fireEvent가 단 한번만 사용됐다면 모르겠는데 여기저기 사용한 파일이었군요. 감사합니다!

2020-11-05 15:19 UTC, juunini commented
# 작업 내용
- 로그인 구현
- 리뷰 service 구현
- 현재까지 테스트 커버리지 100% 달성

# 느낀 점
- 점점 평소 하던 현업과 비슷해져가는 느낌입니다.
  그걸 TDD로 해볼 수 있다는게 참 좋아요. 맨날 하던걸 하는 느낌인데도 새롭게 느껴집니다.

2020-11-06 16:01 UTC, Kihyun92 requested changes

2020-11-07 02:20 UTC, juunini commented on src/components/LoginInput.jsx
> +}
그러네요 그냥 input을 쓰는것과 차이점이 없군요

2020-11-07 02:21 UTC, juunini commented on src/containers/RestaurantReviewContainer.test.jsx
> +        'r',
이쯤 졸면서 하다가 푸시하고 잤던 시점인데 문장을 쓰려다가 못썼나봅니다;;

2020-11-07 15:19 UTC, juunini commented
# 작업 내용
- 레스토랑 리뷰 구현
- 레스토랑 페이지에서 리뷰 나오게 처리
- 로그인 시 accessToken을 sessionStorage에 저장하도록 처리하여 새로고침 해도 세션 유지
- 테스트 커버리지 100% 달성
- E2E 테스트 완료

# 느낀 점
- 이번주는 왠지 시간을 부족하게 할당한건지
  아니면 저번 주 보다 할게 더 많아서 해맨건지 썩 만족스럽게 못한 기분이 드네요...
- 내일 시간 날 때 틈틈히 리펙토링을 해야겠습니다. 역시 마음에 안드네요 ㅠㅠ

2020-11-07 18:32 UTC, Kihyun92 requested changes

2020-11-07 18:32 UTC, Kihyun92 commented on src/components/RestaurantReview.test.jsx
> +  const renderRestaurantReview = ({ score, description }) => render(
의미없는 빈객체를 넘기기 보단, 이곳에서 빈 객체를 default parameter로 지정해줘도 좋을 것 같네요~

2020-11-07 18:32 UTC, Kihyun92 commented on src/containers/RestaurantReviewContainer.jsx
> +  }
return하는 부분에서 삼항 연산자로 처리하는건 어떨까요?

이렇게 예외 처리해줘도 지금 코드량에서는 파악이 쉽지만, 추후에 더 컴포넌트가 커지고 복잡해지는 경우에는 토큰이 없는 경우에 null을 리턴해준다는 처리를 확인하기 위해서는 컴포넌트 내부를 다 파악해야할 것 같아요. 대신 return문 내에서 render해주는 부분들에 대해서 처리해준다면 더 파악하기 쉽지 않을까요?

2020-11-07 18:32 UTC, Kihyun92 commented on src/containers/RestaurantReviewContainer.test.jsx
> +      }));
매 테스트마다 selector를 mocking 해주는 것 같아요. 이 부분을 상위의 beforeEach에서 처리해줄 순 없을까요?

2020-11-07 18:34 UTC, Kihyun92 commented
`마음에 안들지만 '일단 되게 하라 -> 고쳐라 -> 최적화 하라' 하는 패턴`에 맞춰서 해보신 것 정말 좋은 것 같아요~ 비록 완벽하고 마음에 드는 코드는 아니겠지만, 꾸준히 개선해 나가는게 중요한 것 같습니다 👍

2020-11-08 15:10 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~ 👍 
강의 풀이 영상 보시면서 과제 의도를 곱씹어 보시면 좋을 것 같아요 :)

이번 과제 Approve 하겠습니다~

2020-11-09 15:26 UTC, merged