login-apply
CodeSoom/week7-assignment-1 pull request #22
Opened 2020-11-03 09:28 UTC by onys-programmer

2020-11-03 12:03 UTC, onys-programmer commented
TypeError: (0 , _reactRedux.render) is not a function 
에러가 발생하면서 LoginForm을 렌더하지 못하고 있습니다만 원인이 무엇인지 모르겠습니다. 내일 마저 찾아볼 생각입니다.

2020-11-03 15:29 UTC, hannut91 commented
에러의 원인을 찾을 때 내가 확실히 에러가 없다고 확인한 코드와 아직 확인하지 않은 코드로 나눠서 천천히 찾는 연습을 하시면 좋을 것 같습니다.

2020-11-04 14:48 UTC, hannut91 commented
도움이 필요하시면 말씀해주세요 ㅎㅎ

2020-11-05 00:21 UTC, onys-programmer commented
> 도움이 필요하시면 말씀해주세요 ㅎㅎ

어제는 마이다스아이티에 지원하느라 못했네요..ㅎㅎ 오류를 찾아보고 질문드리겠습니다!

2020-11-05 12:28 UTC, onys-programmer commented
일, 육아와 함께 공부하니.. 참 만족할 정도로 공부하기가 힘이 드네요 ㅠㅠ 
멘탈관리에는 성공하고 있다는 것에 위안 삼으려 합니다.

이번주 토요일은 임용고시를 치러 갑니다.. 부모님과 약속한 바라서 안 갈 수는 없고, 시간낭비를 최대한 줄이고 코딩 공부에 매진할 전략을 세워보겠습니다.

2020-11-05 15:32 UTC, hannut91 reviewed
일 때문에 과제 진행이 어려우시군요 ㅠㅜ... 시간을 어떻게 쓸지 잘 계획하시고 실행하시면 좋을 것 같습니다. 도움이 필요하면 말씀해 주세요.

2020-11-05 15:32 UTC, hannut91 commented on src/LoginForm.test.jsx
> +  });
나타내는 데이터는 배열이라서 여러개를 담고 있는데 변수의 이름을 보면 단수를 사용하고 있어서 마치 배열이 아닌 객체나 다른 타입인 것 처럼 보입니다. 변수이름에 복수를 사용하면 변수 이름만 봐도 여러개를 나타낸다는 것을 알 수 있어서 더 쉽게 의도를 드러낼 수 있습니다.

2020-11-06 11:30 UTC, onys-programmer commented
첫 구직 첫 1차 합격에 마음이 붕 떠 1시간 정도 버렸네요.. 부디 내일은 온전히 코딩으로 범벅이 되는 하루가 되기를 바라봅니다...

2020-11-06 15:46 UTC, hannut91 commented
최종합격이어야지 의미가 있기 때문에 그 전까지는 최선을 다해주시면 좋을 것 같습니다

2020-11-07 11:40 UTC, onys-programmer commented
FAIL  src/reducer.test.js
  ● reducer › setAccessToken › encountered a declaration exception

    expect(received).toBe(expected) // Object.is equality

    Expected: "TOKEN"
    Received: undefined

      174 |     const state = reducer(initialState, setAccessToken('TOKEN'));
      175 | 
    > 176 |     expect(state.accessToken).toBe('TOKEN');
          |                               ^
      177 |   });
      178 | });
      179 | 

오류가 나는데 내일 이어서 찾아보겠습니다.

2020-11-07 16:08 UTC, hannut91 requested changes

2020-11-07 16:08 UTC, hannut91 commented on src/LoginForm.test.jsx
> +  });
jest.clearAllMocks 함수를 이용해서 한 번에 모두 초기화하는 것은 어떨까요?

See also
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks

2020-11-07 16:08 UTC, hannut91 commented on src/LoginForm.test.jsx
> +  it('requests log in', () => {
이 함수에서는 로그인을 요청하는지는 알 수 없어요. 이 컴포넌트에서 하는 일만 테스트해야합니다

2020-11-07 16:08 UTC, hannut91 commented on src/LoginFormContainer.test.jsx
> +  it('renders "Log In" button', () => {
테스트에 구현의 구체적인 내용이 들어가 있어서 구현이 조금만 바껴도 테스트이름도 같이 바껴서 유지보수하기 힘들 것 같아요. 단순히 renders login button이라고 해도 이해하기 괜찮을 것 같아요

2020-11-07 16:08 UTC, hannut91 commented on src/LoginPage.test.jsx
> +      <MemoryRouter>
MemoryRouter가 반복적으로 사용되고 있어요. 렌더링하는 함수로 추출하여 중복을 제가하는 건 어떨까요?

2020-11-07 16:08 UTC, hannut91 commented on src/reducer.test.js
> +    const initialState = {
describe만 명시되어 있고 it함수가 빠진 것 같아요.

2020-11-07 16:08 UTC, hannut91 commented on src/reducer.test.js
> +    context('when password is changed', () => {
it함수가 빠진 것 같아요

2020-11-08 07:29 UTC, onys-programmer commented on src/LoginForm.test.jsx
> +  });
알려주셔서 감사합니다! ^^

2020-11-08 15:55 UTC, hannut91 approved these changes
고생하셨습니다. 과제를 진행하면서 생긴 에러에 대해서 어떻게 대처해야할지 많이 생각해보시면 좋을 것 같습니다. 에러가 발생했을 때 에러의 원인을 잘 찾는 것이 중요합니다. 에러가 생길 수 있는 원인은 굉장히 많은데 확실히 내가 에러가 아니라고 파악한 곳과 아직 파악하지 못한 곳을 찾으면서 원인을 명확히 밝혀내야 합니다.

이번 과제를 통해서 무엇을 배우셨나요?

2020-11-09 12:37 UTC, onys-programmer commented
> 고생하셨습니다. 과제를 진행하면서 생긴 에러에 대해서 어떻게 대처해야할지 많이 생각해보시면 좋을 것 같습니다. 에러가 발생했을 때 에러의 원인을 잘 찾는 것이 중요합니다. 에러가 생길 수 있는 원인은 굉장히 많은데 확실히 내가 에러가 아니라고 파악한 곳과 아직 파악하지 못한 곳을 찾으면서 원인을 명확히 밝혀내야 합니다.
> 
> 이번 과제를 통해서 무엇을 배우셨나요?

  하드스킬: 문서를 찾아보면서 useSelector()의 개념을 다시 잡았습니다. 생각보다 이해가 잘되게 친절히 작성되어 있어 공부하며 즐거웠습니다. 딱딱한 어투로 작성되어있을거라 섣불리 판단했는데 아니었습니다. 번역본보다 영어 원문으로 보는게 훨씬 이해가 잘되는 경험을 했습니다. 아마 영어를 마더텅으로 하는 사람이 영어에 적합한 글을 써서 그러리라 추측해봅니다. 앞으로 더욱 빠른 성장을 위해서 영어원문 읽기를 습관화할 생각입니다.

사실 이번주는 "에러 발생 -> 원인 파악 -> 해결"의 과정을 혼자 힘으로 몇 번 해내는 경험을 해 자신감이 생기는 한 주였습니다. 예전에는 에러가 무섭기만 했는데, 이제는 '아, 내가 무언가를 잘못하고있구나, 혹은 내가 무언가를 이해하지 못하고 있구나' 라는 신호로 받아들여져 점점 고맙게 느껴집니다. 

  소프트스킬: 이번주도 어김없이, 높은 벽에 가로막힌 느낌을 받았습니다. 구현량에 압도되었습니다. 딱히 놀지도 않고, 시간을 허비하는 느낌을 받지 않았는데도 생각보다 성취가 굉장히 적어서 우울함도 느꼈습니다. 그 때 한 동기님을 인터뷰했습니다. '항상 과제를 잘 해내는 것을 보면 분명 내가 배울 점이 있을 것이다. 그 동기를 벤치마킹해 돌파구를 찾자' 라는 생각이었습니다. 인터뷰 후 그 분이 하루 12시간동안 공부한다는 것을 알게 되었고 감탄했습니다. 

나는 최선을 다한 줄 알았는데, 최선을 다한 것이 아니었습니다.  물리적 시간 확보가 부족한 상황이라고 힘이 빠진 상태로 조금은 무기력해진 저를 반성하고, 대안으로 집중력, 효율의 확보를 실천하기 위해 전략을 세웠습니다. 

-퇴근 후 바로 공부를 하고 집에 가기. 
-공부 장소는 카페에서 스터디카페로 변경.
-공부 중에 방해될 요소 모두 제거.

2020-11-11 00:17 UTC, hannut91 commented
고생하셨습니다 ㅎㅎ 공부할 수 있는 환경과 쉬는 환경을 구분해주는 건 좋은 것 같아요 ㅎㅎㅎ 저도 집중이 안될때는 카페에가서 많이 합니다.

에러가 발생했을 때 내가 확실히 문제가 없다고 확인한 곳과 확인하지 않은 곳을 확인해가며 찾아보시면 더 찾기 쉬울 것 같아요

2021-01-17 12:40 UTC, merged