Implement Login page and Review
CodeSoom/week7-assignment-1 pull request #23
Opened 2020-11-03 11:13 UTC by gringrape

죄송합니다. 커밋이 꼬였어 리셋하다가 닫혀버렸네요 ㅜ

2020-11-03 14:02 UTC, gringrape commented
## 작업 내용
- 로그인 페이지 (UI) 구현
  - submit 버튼, click 이벤트 처리
  - input 컨트롤, change 이벤트 처리

2020-11-03 15:36 UTC, Kihyun92 reviewed
커밋을 세세하게 잘 적어주셔서 구현 상황을 파악하기 쉽네요! 👍  진행하시다가 막히거나 의논이 필요한 부분이 있다면 말씀주세요~

2020-11-04 13:39 UTC, gringrape commented
## 작업내용
- 로그인폼과 리뷰폼 모두에서 input-control 에 대한 중복이 발생할듯하여, 텍스트 필드로 추상화를 시도했으나 실패.
- 리뷰폼 구현 -> 컨테이너 구현 예정

## 작업후기
- 텍스트필드로 추상화를 하려했으나, 너무 많은 인자를 받아야 하고, 테스트가 줄어드는 것 같지도 않아서 포기했습니다. 
- 리뷰폼을 구현하면서 로그인폼에서 했던 일과 같은 일을 TDD로 하나씩 하니 괴로움을 느꼈습니다. 
지혜롭게 처리하고 싶습니다... 
- 잘 안풀리는 날인데 다시 힘내서 해보겠습니다!

2020-11-04 15:56 UTC, Kihyun92 requested changes
텍스트 필드를 추상화 하는게 쉽지 않을 것 같네요. 🤔오히려 너무 많은 인자를 넘기는 방식으로 추상화 하는것은 좋지 않은 것 같아요. 혹시 불필요하게 넘기는 인자가 없는지 고민해보시고, 오히려 복잡해질땐 과감하게 포기하는 것도 방법일 것 같아요. 😁

그리고 고민하신대로 로그인폼과 리뷰폼은 어느정도 테스트가 겹칠 수 밖에 없다고 생각합니다ㅎㅎ 각각 주요 기능은 다르겠지만, 흐름은 비슷하죠.
테스트 코드라는게 본인이 안심될 때까지 해보는게 중요하기 때문에, 지금처럼 하나씩 해보는 방법을 추천드려요 👍 

그리고 로그인 실패시 에러처리하는 부분에 대해서 고민해보셨네요! 좋습니다👍
음 저는 action에서 fetch해줄 때 try/catch를 이용해서 에러 캐치한 후 에러 발생시 얼럿을 노출해주는 방법도 떠오르네요~

잘 풀리지 않을땐 잠시 휴식을 취한 후 하는걸 추천드려요 ㅎㅎ 개인적으로 저는 오래 몰입하다보면 시야가 좁아지더라구요😭
커밋을 보니 잘 진행하고 계신것 같아요~ 남은 기간도 화이팅하시죠 💪

2020-11-04 15:56 UTC, Kihyun92 commented on src/LoginFormCotainer.test.jsx
> +  const dispatch = jest.fn();
각 테스트들이 영향이 없도록 beforeEach에서 mocking해준 dispatch를 clear 해주면 좋을 것 같네요~

2020-11-04 15:56 UTC, Kihyun92 commented on src/ReviewForm.jsx
> +export default function LoginForm({ fields, onChange, onSubmit }) {
컴포넌트 네이밍이 아직 LoginForm 이네요 ㅎㅎ 수정해주세요~

2020-11-05 15:41 UTC, Kihyun92 requested changes

2020-11-05 15:41 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  describe('login button', () => {
describe 내에 문장이 어떤 테스트인지 명확하게 설명하고 있지 않은 것 같아요. describe를 사용하지 않아도 지금 테스트는 명확하게 전달 가능하지 않을까요?

2020-11-05 15:41 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  describe('input-controls', () => {
해당 테스트에 대해 명확히 알 수 없는 것 같아요. 지금의 상황에서는 굳이 없어도 의도가 드러나는것 같기도하네요 ㅎㅎ 한번 고민해주시면 좋겠습니다~

2020-11-05 15:41 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +    it('are rendered', () => {
`renders input controls`와 같이 조금 더 어떤 테스트인지를 설명해 주는 문장은 어떤가요?

2020-11-05 15:41 UTC, Kihyun92 commented on src/LoginFormContainer.jsx
> +  );
```suggestion
  return (
    <>
      {isLoggedIn ? (
        <button type="button" onClick={handleClickLogOut}>
          Log out
        </button>
      ) : (
        <LoginForm
          fields={loginFields}
          onSubmit={handleSubmit}
          onChange={handleChange}
        />
      )}
    </>
  );
```

지금도 잘해주셨지만, 이렇게 처리해주는건 어떤가요? 개인적으로는 조금 더 명확할 것 같아요~

2020-11-05 15:41 UTC, Kihyun92 commented on src/ReviewForm.test.jsx
> +  describe('input-controls', () => {
```suggestion
  describe('input controls', () => {
```
케밥 케이스를 사용하기보다는 그냥 띄어쓰기로 작성해주는건 어떤가요?

2020-11-05 15:41 UTC, Kihyun92 commented on src/ReviewFormContainer.jsx
> +  );
`return` 안에서 삼항 연산자로 처리해주면 더 명확할 것 같아요~

2020-11-05 15:41 UTC, Kihyun92 commented on src/ReviewFormContainer.test.jsx
> +  context('when logged-in', () => {
```suggestion
  context('when logged in', () => {
```

2020-11-05 15:41 UTC, Kihyun92 commented on src/ReviewFormContainer.test.jsx
> +    it('renders write-review button', () => {
```suggestion
    it('renders write review button', () => {
```

2020-11-05 15:41 UTC, Kihyun92 commented on src/Reviews.jsx
> +  }
리뷰가 없는 경우에 대해서 처리해주신 것 같아요 👍 

이 부분을 `ReviewsContainer`에서 처리해줘도 좋을 것 같고, 아니면 아래 `return` 내에서 `fragment`로 감싸서 삼항연산자로 처리해주는게 좋을 것 같습니다~

그리고 reviews가 있는 경우에 대해서 처리하려면 `reviews?.length`와 같이 옵셔널 체이닝으로 처리해주는게 좋을 것 같습니다!
- https://ko.javascript.info/optional-chaining

2020-11-05 15:57 UTC, gringrape commented
정신없이 하다보니 리뷰도 못봤네요! 맑은 정신으로 다시 읽어보고 반영하겠습니다 감사합니다 :)

2020-11-06 16:06 UTC, Kihyun92 reviewed
storage에 대한 테스트를 작성해보셨군요~ 👍 

진행하시다가 논의가 필요하거나 막히는 부분이 있다면 언제든 말씀해주세요 :)

2020-11-07 12:53 UTC, gringrape commented on src/LoginForm.test.jsx
> +    it('are rendered', () => {
위의 describe 와 함께 input controls are rendered 라는 식으로 읽히도록 구성했고,
describe 를 사용한건 공통된 대상에 대한 테스트를 묶고자 함인데, 
잘 전달이 안되나 보네요. 좀 더 간단하게 구성해 보겠습니다

2020-11-07 13:42 UTC, gringrape commented on src/ReviewFormContainer.jsx
> +  );
guard clause 방법으로 분리해주었는데,
불명확할까요?? 바꿔봤는데 아래쪽이 복잡해지는것 같아서요.

2020-11-07 13:53 UTC, gringrape commented on src/Reviews.jsx
> +  }
```javascript
const reviews = null;
reviews?.length === 0 // false 
```
null 인 경우는 이렇게 되어버리네요? ㅜ

2020-11-07 17:50 UTC, Kihyun92 commented on src/Reviews.jsx
> +  }
그럼 `reviews && reviews.length > 0 ? {리뷰 노출} : '리뷰가 없습니다'` 와 같은식으로 처리해도 괜찮겠네요~

2020-11-07 17:59 UTC, Kihyun92 commented on src/ReviewFormContainer.jsx
> +  );
불명확하다는 의미는 아니었습니다~ ㅎㅎ 
개인적으로 view에 대한 처리는 return 문만 읽어도 이해가 되도록 삼항 연산자로 처리가 가능하면 처리하고, 사용되는 핸들러나 초기화 부분은 컴포넌트 내부에서 처리하는게 더 분리가 된다고 생각해서 드린 말이었습니다~
지금 같은 코드에선 전반적으로 파악하는데 문제가 없지만, 컴포넌트가 더 비대해지고, 예외처리에 필요한 부분이 많아진다면 복잡해질 것 같은데 어떤가요?

2020-11-08 09:35 UTC, gringrape commented on src/ReviewFormContainer.jsx
> +  );
뷰에 대한 로직을 한군데로 몰아주라는 의미군요 ㅎ 컴포넌트가 비대해진다면 확실히 뷰로직이 한군데 있는것이 이해하기 좋을것같습니다. 
의도는 삼항연산자를 사용하면 두경우가 대등한 느낌이 들어서, 예외적인 경우를 위에서 정리해버리고 밑에서는 관심있는걸 한다는 뜻이었는데 혼란이 될수도 있겠군요 ㅎ
감사합니다

2020-11-08 15:06 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~ 강의 풀이 영상 보시면서 과제 의도를 곱씹어 보시면 좋을 것 같습니다 :)

Approve 하겠습니다~ 회고 부탁드려요 ㅎㅎ

2020-11-09 15:25 UTC, merged