[7주차] 레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기
CodeSoom/week7-assignment-1 pull request #25
Opened 2020-11-03 13:01 UTC by oceanide2

- 7주 강의 순서대로 작성해보고 있습니다. 
- 동영상 강의를 본 후에 진행해보고는 있지만 막히는 부분이 있으면 다시 찾아보게 됩니다. 강의에서 진행한 순서의 흐름을 기억해보려고 노력중입니다.
- 7주는 내용이 많아서 모두 구현이 가능할지는 모르겠지만 해볼 수 있을때까지는 해보려고 합니다.

2020-11-03 15:33 UTC, hannut91 reviewed
아샬님은 과제를 해결하려는 시도를 하는 것만으로도 많이 배울 수 있다고 하셨습니다. 아주 잘 진행하고 계신 것 같습니다

2020-11-03 15:33 UTC, hannut91 commented on src/LoginForm.test.jsx
> +  });
테스트의 이름이 구체적인 구현 사항에 의존하고 있습니다. 구현이 조금만 바뀌어도 테스트 뿐만 아니라 테스트의 이름까지 변경될 가능성이 높아보입니다. 

```js
context('when login button is clicked', () => {
  it('calls onClick handler', () => {
    const { getByText } = renderLoginForm();

    fireEvent.click(getByText('Log In'));

    expect(handleSubmit).toBeCalled();
  });
});
```

이건 어떨까요?

2020-11-04 14:44 UTC, hannut91 reviewed
잘 진행하고 계신 것 같습니다 ㅎㅎ

2020-11-04 14:44 UTC, hannut91 commented on src/LoginForm.test.jsx
> +  );
저는 테스트에 사용되는 변수, 상수, 함수들을 위에 정리하고, 테스트 라이프 사이클에 해당하는 `beforeEach` 함수들은 아래에 정리해놓습니다. 어떻게 정리하든 상관없지만, 중간에 섞여있는 것 보다는 정리해보는 것도 좋을 것 같아요

2020-11-04 14:44 UTC, hannut91 commented on src/services/api.test.js
> +  });
`abcd`가 Magic literal인 것 같습니다. Magic literal이란 코드에서 단순한 숫자 혹은 문자열을 직접사용하는 것을 말합니다. 

예를들어서 수강 신청한 학생들이 있는데 신청한 학생들을 선착순 3명까지 자르기로 했습니다.

```js
const applicants = ['윤석', '수형', '기현', '기환', '아샬'];

// 강의를 들을 수 있는 최대 인원은 3명입니다.
const students = applicants.slice(0, 3);

console.log(students); // [ '윤석', '수형', '기현' ]
```

그래서 3명의 학생들이 걸러졌습니다. 하지만 코드만 보면 왜 3명이지? 4명이나 5명은 안되는지 알 수 없습니다. 주석을 달아서 설명했습니다. 딱히 문제는 없어보입니다. 하지만 만약 강의 정원을 늘리던지, 줄이면 주석도 수정해야하고 코드도 수정해야합니다. 

중복이 발생한 겁니다. 최악의 경우는 주석과 코드가 다를 경우 입니다. 테스트코드가 없다면 주석이 맞는건지 코드가 맞는건지 아무도 판별할 수 없습니다. 

그렇다면 주석없이 같은 표현을 하려면 어떻게 해야할까요?

```js
const LECUTRE_LIMIT = 3;

const applicants = ['윤석', '수형', '기현', '기환', '아샬'];

const students = applicants.slice(0, LECUTRE_LIMIT);

console.log(students); // [ '윤석', '수형', '기현' ]
```
Magic literal을 표현하는 상수를 만들면 됩니다. 이러면 주석이 없어도 왜 3명인지, 지원자들을 자를 때 무엇을 기준으로 자르는지 의도가 바로 드러납니다.

`abcd`, `test@test.com`, `test`는 Magic literal이고 테스트를 이해하는데 도움이 되지는 않는 것 같습니다. 상수로 분리하면 다음과 같이 표현할 수 있을 것  같아요.

```js
describe('postLogin', () => {
  const mockAccessToken = 'abcd';
  const email = 'test@test.com';
  const password = 'test';

  beforeEach(() => {
    mockFetch({ accessToken: mockAccessToken });
  });

  it('returns accessToken', async () => {
    const accessToken = await postLogin({ email, password });

    expect(accessToken).toBe(mockAccessToken);
  });
});
```

제가 작성한 코드가 정답은 아닙니다. 때로는 그냥 텍스트를 보여주는 것이 오히려 더 이해가 쉬울 수 있어요. 특히 컴포넌트 테스트에서는 텍스트를 그대로 보여주는게 더 이해가 쉬울 수 있습니다.

강박적으로 Magic literal을 없애기 보다는 테스트가 얼마나 이해하기 쉬운가? 에 대해서 고민하면서 테스트를 작성해보시면 좋을 것 같습니다. 정답은 없습니다

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html

2020-11-05 14:57 UTC, hannut91 requested changes

2020-11-05 14:57 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +      });
명확한 의도가 없다면 변수를 선언한 곳과 사용하는 곳의 거리는 가까워야 합니다. 

```js
const lectureId = 1004;

const lecture = getLecture(lectureId);

const isLogin = didLogin();
if (!isLogin) {
  alert('로그인을 해주세요.');
  return;
}

if (!didBuyLecture(lecture)) {
  alert('강의를 먼저 구매해주세요.');
  return;
}

showLecture(lectureId);
```

위의 예제를 보면 lecture 를 선언한 곳과 이 lecture를 사용하는 didByLecture(lecture) 와의 거리가 멀리 떨어져있습니다. 그러면 변수가 언제 사용되는지 오래동안 기억하고 있어야 하고, 사용되는 코드를 볼 때 다시 이 변수가 어디에서 왔는지 확인해야 합니다.

거리가 가까우면 한눈에 보이고 왜 이 변수가 선언되었는지 파악하기 쉽습니다.  lecture를 선언한 것을 변수를 사용하는 곳 바로 옮기면 아래와 같이 됩니다.

```js
const lectureId = 1004;

const isLogin = didLogin();
if (!isLogin) {
  alert('로그인을 해주세요.');
  return;
}

const lecture = getLecture(lectureId);
if (!didBuyLecture(lecture)) {
  alert('강의를 먼저 구매해주세요.');
  return;
}

showLecture(lectureId);
```

`inputs`를 선언한 곳과 사용하는 곳이 떨어져있는데, 가까이 붙이면 좋을 것 같습니다. 혹은 만약 테스트에 필요한 데이터를 선언한 것이라면 꼭 가까이 선언하지 않아도 되고, 그렇다면 의도적으로 더 떨어트려놓는게 좋다고 생각합니다.

```js
context('with review change event', () => {
  const inputs = [
    { label: '평점', name: 'score', value: '5' },
    { label: '리뷰 내용', name: 'description', value: '정말 최고!' },
  ];
  
  given('restaurant', () => ({
    id: 1,
    name: '마법사주방',
    address: '서울시 강남구',
  }));

  it('dispatch changeReviewField', () => {
    const { getByLabelText } = renderRestaurantContainer();

    inputs.forEach(({ label, name, value }) => {
      fireEvent.change(getByLabelText(label), {
        target: { value },
      });

      expect(dispatch).toBeCalledWith({
        type: 'changeReviewField',
        payload: { name, value },
      });
    });
  });
});
```

2020-11-05 14:57 UTC, hannut91 commented on src/ReviewForm.test.jsx
> +  context('with review button is clicked', () => {
리뷰 버튼이 클릭되었을 때 테스트를 작성해주신 것 같아요. `with`대신 `when`을 사용하여 `when review button is clicked`는 어떨까요? 혹은 다음과 같이 쓰는 것 중에 어떤게 더 좋은가요?

```js
describe('Click review button', () => {
  it('calls onClick handler', () => {
    // ...
  });
});
```

2020-11-05 14:57 UTC, hannut91 commented on src/services/api.js
> +  console.log(accessToken);
테스트하는데 값을 확인하기 위해 사용하신 것 같아요. 실제 코드에서는 지우는게 좋을 것 같습니다.

2020-11-06 10:58 UTC, oceanide2 commented
- Reviews.map을 할 때 destructing을 하면 eslint에서 에러가 발생합니다. destructing 개수가 4개가 되면 그렇게 되는 것 같은데 왜 에러가 나는지 이유를 모르겠네요. 
```
export default function Reviews({ reviews }) {
  return (
    <ul>
      {reviews.map((review) => (
        <li key={review.id}>
          <p>{review.name}</p>
          <p>{review.score}</p>
          <p>{review.description}</p>
        </li>
      ))}
    </ul>
  );
}
```

2020-11-06 15:33 UTC, hannut91 requested changes

2020-11-06 15:33 UTC, hannut91 commented on src/Reviews.test.jsx
> +});
테스트를 작성할 때는 모든게 올바르게 동작하는 경우인 Happy path를 먼저 작성하고 난 후 나머지 다른 예외 케이스를 단계적으로 구현하는 것이 좋습니다. 왜냐하면 처음부터 너무 많은 기능을 생각하거나 이것저것 예외케이스를 생각하다보면 복잡성 압도당하여 코딩을 시작하기 어렵게 됩니다. 

먼저 모든게 올바르게 동작하는 경우를 테스트를 작성합니다.

```js
describe('Restaurants', () => {
  it('renders restaurants', () => {
    const restaurants = [
      { id: 1, name: '마녀주방', category: '한식', address: '강남' },
    ];

    const { container } = render(<Restaurants restaurants={restaurants}/>);
    
    expect(container).toHaveTextContent('마녀주방');
    expect(container).toHaveTextContent('한식');
    expect(container).toHaveTextContent('강남');
  });
});
```

그 다음에 만약에 레스토랑 목록이 비어있으면 어떻게 되지? 만약에 레스토랑 목록중에 카테고리가 입력이 안되있는 경우에는 어떡하지? 같은 경우가 생각이 날 수 있습니다. 현재는 어떻게 동작하지 정의되어 있지 않습니다. 따라서 테스트를 작성하여 정의내릴 수 있습니다.

```js
describe('Restaurants', () => {
  context('with restaurants', () => {
    const restaurants = [
      { id: 1, name: '마녀주방', category: '한식', address: '강남' },
    ];

    it('renders restaurants', () => {
      const { container } = render(<Restaurants restaurants={restaurants} />);

      expect(container).toHaveTextContent('마녀주방');
      expect(container).toHaveTextContent('한식');
      expect(container).toHaveTextContent('강남');
    });
  });

  context('when restaurants is empty', () => {
    const restaurants = [];

    it('renders empty message', () => {
      const { container } = render(<Restaurants restaurants={restaurants} />);

      expect(container).toHaveTextContent('레스토랑이 없습니다.');
    });
  });
  
  // TODO
  context('when restaurants is null', () => {
    it('renders empty message', () => {
      // ...
    });
  });
});
```

그러면 테스트가 실패할 것이고 이 테스트가 통과하도록 기능을 구현하면 됩니다. 그래서 테스트가 스펙이 되고, 살아있는 문서가 됩니다.

Happy path는 잘 작성해주셨고 다양한 케이스를 시도해보시면 좋을 것 같습니다.

2020-11-06 15:33 UTC, hannut91 commented on src/services/api.test.js
> +    const mockAccessToken = 'abcd';
`mockAccessToken`은 위에서도 아래에서도 사용되고 있어서 중복이 발생했습니다. 위로 분리해서 중복을 제거하는 것이 어떨까요? 테스트코드도 코드이기 때문에 잘 관리하지 않으면 유지보수하기 상당히 힘들어집니다.

2020-11-07 16:10 UTC, hannut91 commented
도움이 필요하시면 말씀해주세요 ㅎㅎ

2021-01-17 12:40 UTC, merged