Week_7 restaurant review TDD [진행중]
CodeSoom/week7-assignment-1 pull request #26
Opened 2020-11-03 13:28 UTC by saseungmin

## 🚀 레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기

### 📌 과제 목표
- [ ] TDD로 기능 구현
- [ ] 커버리지 100% 달성
- [ ] 로그인 페이지 구현
- [ ] 로그인 구현
- [ ] 리뷰 작성하기 구현
- [ ] 리뷰 목록 조회하기 구현

2020-11-03 15:27 UTC, hannut91 requested changes

2020-11-03 15:27 UTC, hannut91 commented on src/LoginForm.test.jsx
> +    });
테스트의 이름이 구체적인 구현 사항에 의존하고 있습니다. 구현이 조금만 바뀌어도 테스트 뿐만 아니라 테스트의 이름까지 변경될 가능성이 높아보입니다. 

구체적인 구현을 테스트하기 보다는 어떤 일이 벌어지는지, 어떤 변화가 일어나는지에 더 집중해서 테스트 이름을 지어보시면 좋을 것 같습니다.

2020-11-03 15:27 UTC, hannut91 commented on src/LoginForm.test.jsx
> +    });
`getBy*`함수는 모든 노드중에 텍스트 노드를 가지고 있고, 그리고 그 텍스트 노드의 `textContent`와 비교해서 찾는 함수입니다. 간단히 텍스트가 존재하는지 확인할 때는 다음과 같이 하는게 좋을 것 같습니다.

```js
expect(container).toHaveTextContent('Some text');
```

See also
  * https://github.com/testing-library/jest-dom#tohavetextcontent
  * https://testing-library.com/docs/dom-testing-library/api-queries#getby

2020-11-03 23:49 UTC, hannut91 commented on src/ErrorMessage.test.jsx
> +    expect(container).toHaveTextContent('입력이 안된 사항이 있습니다.');
컴포넌트 테스트에서는 사실 텍스트를 그대로 보여주면 좋은 케이스가 많긴 한데, 위에 변수 `message`를 선언한 것이 있어서 말씀드려봤어요 ㅎㅎ

2020-11-04 14:48 UTC, hannut91 commented
도움이 필요하시면 말씀해 주세요

2020-11-04 15:29 UTC, saseungmin commented on src/ErrorMessage.test.jsx
> +    expect(container).toHaveTextContent('입력이 안된 사항이 있습니다.');
- 자세한 설명 감사합니다 ㅠㅠ 🙏🙏🙏

그러면 `LoginForm.jsx`에서도 마찬가지로 
```javascript
const ERROR_MESSAGE = '입력이 안된 사항이 있습니다.';

// 생략...
{error && <ErrorMessage message={ERROR_MESSAGE} />}
```
위와 같이 변경해줘야 되는 건가요??

2020-11-05 15:23 UTC, hannut91 commented on src/ErrorMessage.test.jsx
> +    expect(container).toHaveTextContent('입력이 안된 사항이 있습니다.');
대부분의 경우에는 상수로 분리합니다 ㅎㅎ

2020-11-05 15:30 UTC, hannut91 requested changes

2020-11-05 15:30 UTC, hannut91 commented on src/LoginForm.jsx
> +  const ERROR_MESSAGE = '입력이 안된 사항이 있습니다.';
상수로 분리해주셨네요 ㅎㅎ 앱이 점점 거대해질수록 이런 상수의 사용이 많아질 것이고 그러면 이 상수를 정의하는 곳이 이 컴포넌트가 맞나? 생각이 들것이고 그러면 다른 곳으로 분리해야겠다는 생각이 들거에요

2020-11-05 15:30 UTC, hannut91 commented on src/LoginFormContainer.test.jsx
> +    });
테스트의 이름이 구체적인 구현 사항에 의존하고 있습니다. 구현이 조금만 바뀌어도 테스트 뿐만 아니라 테스트의 이름까지 변경될 가능성이 높아보입니다. 

구체적인 구현을 테스트하기 보다는 어떤 일이 벌어지는지, 어떤 변화가 일어나는지에 더 집중해서 테스트 이름을 지어보시면 좋을 것 같습니다.

2020-11-05 15:30 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +      ];
나타내는 데이터는 배열이라서 여러개를 담고 있는데 변수의 이름을 보면 단수를 사용하고 있어서 마치 배열이 아닌 객체나 다른 타입인 것 처럼 보입니다. 변수이름에 복수를 사용하면 변수 이름만 봐도 여러개를 나타낸다는 것을 알 수 있어서 더 쉽게 의도를 드러낼 수 있습니다.

2020-11-05 15:53 UTC, saseungmin commented on src/LoginFormContainer.test.jsx
> +    });
수정하겠습니다.. 자꾸 놓치게 되네요

2020-11-05 15:54 UTC, saseungmin commented on src/RestaurantContainer.test.jsx
> +      ];
이 부분도 전에 받았던 리뷰인데 같은 실수를 했네요.. 내일 수정하겠습니다.

2020-11-05 15:57 UTC, saseungmin commented
- 리뷰해주신 사항들은 내일 수정하겠습니다.
- 한가지 질문이 있습니다.
아래 localStorage에 관한 테스트는 어떻게 해줘야할까요?
```javascript
// storage.js
export function saveItem(key, value) {
  localStorage.setItem(key, value);
}

export function loadItem(key) {
  return localStorage.getItem(key);
}
```

2020-11-06 15:42 UTC, hannut91 commented
storage 테스트는 간단히 잘 동작하는지만 테스트하면 좋을 것 같아요. 

```js
test('storage', () => {
  saveItem('accessToken', 'ACCESS_TOKEN');

  expect(loadItem('accessToken')).toBe('ACCESS_TOKEN');

  removeItem('accessToken');

  expect(loadItem('accessToken')).toBeNull();
});
```

`localStorage`의 wrapper라서 어떤 일을 하는지 명세하는 역할로만 간단하게 테스트를 작성하면 좋을 것 같습니다

2020-11-06 15:49 UTC, hannut91 requested changes

2020-11-06 15:49 UTC, hannut91 commented on src/services/storage.test.js
> +});
테스트 대상을 mocking하면 아무런 테스트가 되지 않습니다. 테스트를 코드의 예제라고 생각해보시고 누군가에 이 코드를 어떻게 사용하는 것인지 예제를 보여준다고 생각하고 작성해보시면 좋을 것 같습니다.

2020-11-06 15:49 UTC, hannut91 commented on src/reducer.test.js
> +  });
이 코드를 실행하면 어떤 일이 발생하는지 어떤 변화가 일어나는지 기술해주시면 좋을 것 같습니다

2020-11-06 15:49 UTC, hannut91 commented on src/reducer.test.js
> +    });
여기도 마찬가지로 어떤 일이 일어나는지 기술해주시면 좋을 것 같습니다

2020-11-06 15:49 UTC, hannut91 commented on src/reducer.test.js
> +    context('when email is changed', () => {
여기도 어떤 일이 일어나는지 작성해주세요

2020-11-06 18:01 UTC, saseungmin commented
- 코드리뷰해주신 사항들과 리팩토링은 내일 진행하도록 하겠습니다.

2020-11-07 16:33 UTC, hannut91 requested changes

2020-11-07 16:33 UTC, hannut91 commented on src/App.test.jsx
> +  context('when logged in', () => {
반대로 된 것 같아요. 이 경우가 로그인 된 경우고 아래가 로그아웃 한 경우죠?

2020-11-07 16:33 UTC, hannut91 commented on src/LoginForm.test.jsx
> +    it('called at the click of a button', () => {
과겨형으로 적기보다는 현재 어떤 일을 하는지 적어주면 좋을 것 같아요. click login button calls onSubmit handler는 어떨까요?

2020-11-07 16:33 UTC, hannut91 commented on src/LoginFormContainer.test.jsx
> +describe('LoginFormContainer', () => {
상황에 따라서 다른 테스트를 작성할 떄 `context`를 이용해서 구분하고, 어떤 테스트인지를 명시할 때는 `describe`를 이용해서 명시해주면 더 좋을 것 같아요.

그리고 로그인 했을 때 테스트 이름이 잘못된 것 같아 수정해봤어요

```js
describe('LoginFormContainer', () => {
  const dispatch = jest.fn();

  beforeEach(() => {
    dispatch.mockClear();

    useDispatch.mockImplementation(() => dispatch);

    useSelector.mockImplementation((selector) => selector({
      loginFields: given.loginFields,
      accessToken: given.accessToken,
    }));
  });

  const renderLoginPage = () => render(<LoginFormContainer />);

  context('when logged out', () => {
    given('accessToken', () => '');

    it('renders input controls', () => {
      const { getByLabelText } = renderLoginPage();

      expect(getByLabelText('E-mail').value).toBe('tester@example.com');
      expect(getByLabelText('Password').value).toBe('test');
    });

    context('with valid email and password', () => {
      given('loginFields', () => ({
        email: 'tester@example.com',
        password: 'test',
      }));

      describe('Change input', () => {
        it('dispatches changeLoginField action', () => {
          const { getByLabelText } = renderLoginPage();

          fireEvent.change(getByLabelText('E-mail'), {
            target: { value: 'new email' },
          });

          expect(dispatch).toBeCalledWith({
            type: 'changeLoginField',
            payload: { name: 'email', value: 'new email' },
          });
        });

        describe('Click login button', () => {
          it('renders login button', () => {
            const { getByText } = renderLoginPage();

            fireEvent.click(getByText('Log In'));

            expect(dispatch).toBeCalledTimes(1);
          });
        })
      });
    });

    context('with invalid email and password', () => {
      given('loginFields', () => ({
        email: '',
        password: 'test',
      }));

      describe('Click login button', () => {
        it('Click "Log In" button nothing happen', () => {
          const { getByText } = renderLoginPage();

          fireEvent.click(getByText('Log In'));

          expect(dispatch).not.toBeCalled();
        });
      });
    });
  });

  context('when logged in', () => {
    given('accessToken', () => 'ACCESS_TOKEN');

    describe('Click logout button', () => {
      it('dispatches logout action', () => {

        const { getByText } = renderLoginPage();

        fireEvent.click(getByText('Log out'));

        expect(dispatch).toBeCalledWith({ type: 'logout' });
      });
    });
  });
});
```

2020-11-07 16:33 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +          expect(container).toHaveTextContent(NO_REVIEW_TEXT);
이 경우에는 그냥 텍스트로 보여주는게 테스트를 이해하는데 더 도움이 될 거 같아요

2020-11-08 09:24 UTC, saseungmin commented
- github test fail이 났을시 re run는 어디서하는 걸까요?
- https://github.com/CodeSoom/week6-assignment-1/pull/26#pullrequestreview-521152816
- 어디서하는지 못찾겠습니다..

2020-11-08 15:30 UTC, hannut91 commented
권한이 없어서 아마 안되실거에요 ㅠㅜ..

2020-11-08 15:54 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 아마 서버에서 적절히 응답을 하지 않는 경우에 CI에서 테스트가 실패할 수 있습니다. 이런 경우 fake API로 테스트를 진행해서 테스트가 외부 상황에 따라 실패하지 않도록 할 수 있습니다.

이번 과제를 통해서 무엇을 배우셨나요?

2020-11-08 23:42 UTC, saseungmin commented
- 이번주 코드리뷰 감사합니다~!!🙏
- 회고 작성하였습니다!!

2020-11-11 00:18 UTC, merged

2020-11-11 00:18 UTC, hannut91 commented
채널에 회고를 남겨주셔서 머지합니다 ㅎㅎ 고생하셨습니다