[Week7] Assignment 1 - 레스토랑 로그인 구현
CodeSoom/week7-assignment-1 pull request #31
Opened 2020-11-04 13:54 UTC by wjy5446

# 과제 목표
TDD로 기능 구현
커버리지 100% 달성
로그인 페이지 구현
로그인 구현
리뷰 작성하기 구현
리뷰 목록 조회하기 구현

# 진행사항
- [x] 강의 수업 듣기 1
- [ ] 강의 수업 듣기 2
- [ ] 강의 수업 듣기 3

2020-11-04 14:47 UTC, hannut91 commented on src/actions.js
> +};
```suggestion
};

// Add some code
```

코드 마지막 줄에는 빈 줄이 하나가 추가되어야 합니다. 그렇지 않으면 위와 같이 GitHub에서 표시가 되고 또한 eslint에서 통과하지 못합니다. 


빈 줄을 추가해야하는 이유는 GitHub의 컨벤션 때문에 그렇습니다. GitHub은 변경사항을 표시할 때 변경전 부분과 변경 후 를 모두 보여줍니다. 

```
console.log('Hello');
```

만약 위와 같이 빈 줄이 없는 코드에서 아래에 코드를 추가하게 되면 GitHub은 다음과 같이 표시합니다.

```
- console.log('Hello');
+ console.log('Hello');
+ console.log('world!');
```

저는 단순히 아래 한 줄만 추가했는데 왜 세줄이 변경되었다고 나오는 걸까요? 그 이유는 줄바꿈 문자 \n가 들어갔기 때문입니다. 

```js
- console.log('Hello');
+ console.log('Hello');\n
+ console.log('world');
```

만약 미리 빈 줄을 하나 추가한 상태에서 아래에 새로운 코드를 작성할 경우에는 다음과 같이 보여집니다.

```js
+ console.log('world');
```

이미 \n이 추가되어 있기 때문이죠. 따라서 코드 마지막 줄에 빈 줄 하나를 항상 추가해주는게 좋습니다.

2020-11-05 15:20 UTC, hannut91 requested changes

2020-11-05 15:20 UTC, hannut91 commented on src/RestaurantContainer.jsx
> +      ) : null}
3항 연산자는 앞의 조건이 참이면 앞의 값을 반환하고 거짓이면 뒤의 값을 반환합니다. 앞의 조건일 경우 컴포넌트를 렌더하고 거짓일 경우 아무것도 렌더하지 않기 위해 사용하신 것 같습니다. 이런 경우에는 JavaScript의 `&&`연산자를 사용해서 더 간단하게 표현할 수 있습니다.

```js
// 3항 연산자를 이용해서 표현
{
  restaurants.length > 0
    ? <Restaurants restaurants={restaurants} />
    : null
}

// && 연산자를 이용해서 표현
{restaurants.length > 0 && (
  <Restaurants restaurants={restaurants} />
)}
```

JavaSciprt에서  `&&`연산자는 앞의 값이 `falsy`이면 뒤의 값은 평가하지 않고 앞의 결과를 반환합니다. `truthy`이면 뒤의 값을 반환합니다. 따라서 위의 예제에서 `restaurants`의 길이가 1보다 작으면 결과는 `false`이므로 뒤의 값은 평가하지 않고 `false`를 반환합니다. JSX에서 `false`, `null`, `undefined`, `true`는 아무것도 렌더링하지 않습니다. 따라서 주어진 조건에만 렌더링할 수 있습니다.

하지만 주의할 점도 있습니다. 숫자 `0`은 평가하면 `falsy이지만 `0`자체를 렌더합니다. 예를들어서

```js
{restaurants.length && (
  <Restaurants restaurants={restaurants} />
)}
```

위와 같이 작성하면 길이가 `0`일 때 `falsy`이므로 뒤의 값을 평가하지 않고 앞의 결과를 반환하지만, 숫자 `0`은 JSX에서 렌더링 되므로 원하지 않는 결과가 나올 수 있으므로 주의해야 합니다.

See also
  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND
  - https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored

2020-11-06 15:40 UTC, hannut91 requested changes

2020-11-06 15:40 UTC, hannut91 commented on src/LoginFormContainer.jsx
> +      ))}
선택의 문제이지만 이렇게도 표현할 수 있을 것 같아요

```js
{
  accessToken && (
    <LogoutForm onClick={handleClickLogout} />
  )
}
{
  !accessToken && (
    <LoginForm
      fields={{ email, password }}
      onChange={handleChange}
      onSubmit={handleSubmit}
    />
  )
}
```

2020-11-06 15:40 UTC, hannut91 commented on src/LoginFormContainer.test.jsx
> +    });
이 테스트 이름도 구현에 의존한 이름인 것 같아요. 간단히 `로그인 버튼이 보입니다`로 하는건 어떨까요?

2020-11-06 15:40 UTC, hannut91 commented on src/ReviewForm.test.jsx
> +  it('change 이벤트가 발생하면, handleChange가 호출됩니다.', () => {
평점을 변경하면 onChange handler가 호출됩니다는 어떨까요?

2020-11-07 05:33 UTC, wjy5446 commented on src/actions.js
> +};
이전에도 이런 실수가 있었는데, 또 이렇게 되었네요.
빨리빨리 하려고 하다보니 실수가 나온것 같네요;;

2020-11-07 05:39 UTC, wjy5446 commented on src/RestaurantContainer.jsx
> +      ) : null}
`%%`과 `||` 기존 언어에서 많이 사용하지 않아서 항상 헷갈리네요.
항상 쓰는 버릇을 들여야 겠네요.

2020-11-07 05:42 UTC, wjy5446 commented on src/LoginFormContainer.jsx
> +      ))}
이것도 `&&`연산자로 표현하면 좋겠네요. !!

2020-11-07 05:46 UTC, wjy5446 commented on src/LoginFormContainer.test.jsx
> +    });
굳이 문구로 나타내서 표현할 필요가 없겠네요.!!

2020-11-07 05:47 UTC, wjy5446 commented on src/ReviewForm.test.jsx
> +  it('change 이벤트가 발생하면, handleChange가 호출됩니다.', () => {
이게 더 테스트 코드를 이해하기 쉽네요.!!

2020-11-07 17:34 UTC, hannut91 requested changes

2020-11-07 17:34 UTC, hannut91 commented on src/services/storage.test.js
> +});
`localStorage`자체를 mocking하는 것 보다는 단순히 wrapper로 감싼 코드가 올바르게 동작하는지 아니면 어떤 일을 하는지 정도만 테스트를 작성해줘도 좋을 것 같아요

```js
test('storage', () => {
  const key = 'accessToken';
  const value = 'ACCESSTOKEN';

  saveItem(key, value);

  expect(loadItem(key)).toBe(value);

  deleteItem(key);

  expect(loadItem(key)).toBeNull();
});
```

2020-11-07 17:34 UTC, hannut91 commented on src/services/api.test.js
> +import LOGINFIELDS from '../../fixtures/loginFields';
`LOGIN_FIELDS`라고 하면 더 잘 보일 것 같아요

2020-11-07 17:34 UTC, hannut91 commented on src/reducer.test.js
> +  });
테스트 이름만 명시되어 있고 실제로 어떤 일이 일어나는지 명시안되있네요. `it`함수를 이용해서 어떤 일이 발생하는지 작성해주세요

2020-11-07 17:34 UTC, hannut91 commented on src/reducer.test.js
> +    it('AccessToken을 설정합니다.', () => {
변수 이름인 `accessToken`이 맞을 것 같네요.

2020-11-07 17:34 UTC, hannut91 commented on src/reducer.test.js
> +    });
`password`가 바뀌는 경우 무슨 일이 일어나는지 `it`함수를 이용해서 표현해주세요.

2020-11-07 17:34 UTC, hannut91 commented on src/reducer.test.js
> +    });
`email`이 바뀌는 경우 무슨일이 일어나는지 `it`함수를 이용해서 작성해주세요

2020-11-07 17:34 UTC, hannut91 commented on src/actions.test.js
> +      it('setaccessToken이 호출됩니다.', async () => {
`setAccessToken`이 맞을 것 같아요

2020-11-07 17:34 UTC, hannut91 commented on src/TextField.test.jsx
> +describe('TextField', () => {
컴포넌트를 렌더하는 코드가 가로로 너무 길어서 읽기 어려운 것 같아요. 변경되는 부분만 적용할 수 있도록 추출하면 더 읽기 좋은 코드가 될 것 같아요

```js
describe('TextField', () => {
  const label = '평점';

  const handleChange = jest.fn();

  const renderTextField = (type) => render((
    <TextField
      type={type}
      label={label}
      name="score"
      onChange={handleChange}
    />
  ))

  context('with type', () => {
    it('type이 number인 input을 렌더합니다.', () => {
      const { container } = renderTextField('number');

      expect(container).toContainHTML('type="number"');
    });
  });

  context('without type', () => {
    it('기본값으로 type이 text인 input이 렌더 됩니다.', () => {
      const { container } = renderTextField();

      expect(container).toContainHTML('type="text"');
    });
  });

  describe('Change input', () => {
    it('onChange handler를 호출합니다.', () => {
      const { getByLabelText } = renderTextField('number');

      fireEvent.change(getByLabelText(label), {
        target: { value: 5 },
      });

      expect(handleChange).toBeCalled();
    });
  });
});
```

2020-11-07 17:34 UTC, hannut91 commented on src/ReviewsDetail.jsx
> +            <br />
`<br />`을 사용하기 보다는 `span`대신 `p`를 사용하는게 좋을 것 같아요

2020-11-08 04:41 UTC, wjy5446 commented on src/LoginForm.test.jsx
> +  it('"Log in" 버튼이 보입니다.', () => {
이것도 그대로 쓰는 게 좋겠네요.

2020-11-08 04:44 UTC, wjy5446 commented on src/services/storage.test.js
> +});
저는 fetch도 mocking 하길래 생각없이 localStorage도 mocking하는 것 좋을 것 같아서 작성했네요.

2020-11-08 04:55 UTC, wjy5446 commented on src/services/api.test.js
> +import LOGINFIELDS from '../../fixtures/loginFields';
LOGINFIELDS는 반으로 나누는 게 좋을 것 같네요.

2020-11-08 05:05 UTC, wjy5446 commented on src/reducer.test.js
> +    });
it이 빠졌네요. context을 it으로 바꿔야 겠네요.

2020-11-08 05:05 UTC, wjy5446 commented on src/reducer.test.js
> +    });
it이 빠졌네요. context을 it으로 바꿔야 겠네요.

2020-11-08 05:05 UTC, wjy5446 commented on src/actions.test.js
> +      it('setaccessToken이 호출됩니다.', async () => {
오타네요. 감사합니다.

2020-11-08 05:07 UTC, wjy5446 commented on src/reducer.test.js
> +    it('AccessToken을 설정합니다.', () => {
오타네요. 수정하겠습니다.

2020-11-08 05:11 UTC, wjy5446 commented on src/reducer.test.js
> +  });
it 함수를 빼먹었네요.

2020-11-08 05:14 UTC, wjy5446 commented on src/ReviewsDetail.jsx
> +            <br />
p를 사용하는 게 더 편하겠네요.

2020-11-08 05:19 UTC, wjy5446 commented on src/TextField.test.jsx
> +describe('TextField', () => {
함수로 작성하면 더 편하겠네요.!!

2020-11-08 15:50 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 이번 과제를 통해서 무엇을 배우셨나요?

2020-11-08 15:50 UTC, hannut91 commented on src/App.test.jsx
> +          }],
레스토랑 정보나 리뷰 정보도 fixture분리하면 좋을 것 같아요

2020-11-08 15:50 UTC, hannut91 commented on src/LoginForm.test.jsx
> +  const onSubmit = jest.fn();
props의 이름이 `onChage`, `onSubmit`이라서 mocking 함수의 이름도 똑같이 지으신 것 같아요.
우리가 컴포넌트에서 `handle*` 이라고 이름을 붙이는 이유는 특정 이벤트가 발생했을 때 그 이벤트를 처리하는 함수이기 때문입니다. 

```js
function handleClick() {
  alert('버튼이 클릭됐어요!');
}

<Button onClick={handleClick} />
```

위의 예제를 보면 보면 Click 했을 때 handleClick이 처리한다 라고 읽을 수 있습니다. 따라서 handler함수 이름을 `handleChange`, `handleSubmit`이라고 이름짓는게 좋을 것 같습니다.

2020-11-09 13:37 UTC, wjy5446 commented on src/LoginForm.test.jsx
> +  const onSubmit = jest.fn();
handle로 mock함수명을 바꾸는 게 낫겠네요. 감사합니다.

2020-11-09 13:38 UTC, wjy5446 commented on src/App.test.jsx
> +          }],
fixture로 분리하겠습니다. !!

2020-11-09 13:58 UTC, wjy5446 commented
7주차 회고

1. 한 일
- TDD 실습
- localStorage
- JWT 인증

2. 배운점
- 삼항 연산자 대신에 `&&` 또는 `||`을 이용해서 코드 작성
- 테스트코드 명도 명확하게 작성하는 게 중요
- 핸들러 함수 명을 반드시 `handle ~`로 작성하기

3. 느낀 점 & 자기 선언
- 이번 수업은 인증에 대한 부분에 대해서 배울 수 있었다. 이번 주차는 거의 수업 따라가기에만 바쁜 주차였다. 강의를 들으면서 코드를 작성하다 보니 많이 실수가 있었다. (이를 멘토 분들이 잘 집어내어서 알 수 있었다. ㅠㅠ ) 역시 코드를 작성할 때에는 조급해 하면 않되는 것 같다. 
- 그래도 직접 아샬님의 코드 작성을 따라하면서 TDD에 대한 흐름을 쫓아 갈 수 있어서 좋았다.

2020-11-11 00:20 UTC, merged

2020-11-11 00:20 UTC, hannut91 commented
고생하셨습니다 ㅎㅎ 코드 리뷰를 통해 실수를 잡아서 다행이네요 ㅎㅎㅎ 저는 셀프코드리뷰를 하며 실수를 발견하려고 최대한 노력합니다. 그래도 다른 사람이 봐주는게 훨씬 좋긴 하지만요.