week7-1 Implement Restaurant App
CodeSoom/week7-assignment-1 pull request #33
Opened 2020-11-05 07:35 UTC by JamieShin0201

안녕하세요 ^_^

PR를 너무 늦게 보내네요 ㅠㅠ

현재 로그인, 로그아웃을 구현한 상태입니다.

계속해서 레스토랑 리뷰 작성하는 부분 구현하겠습니다.

감사합니다 ㅎ.ㅎ

2020-11-05 16:02 UTC, Kihyun92 requested changes
TDD를 잘 수행하고 계신것 같아요~ 👍 커밋도 잘 쪼개주셔서 어떻게 작업 중인지 흐름을 파악하기도 좋네요! 남은 기능들도 잘 구현해보시면 좋겠습니다~

2020-11-05 16:02 UTC, Kihyun92 commented on src/reducer.test.js
> +    it('changes email', () => {
상위에 `context`를 사용해서 어떤게 변경됐을때, 어떻게 됐다는 식으로 나타내는건 어떨까요?

2020-11-06 16:25 UTC, Kihyun92 requested changes
너무 잘해주고 계셔요!

storage에 대해서도 테스트해주셨네요 👍 다만 저희가 생각하기에 단순히 커버리지 100%를 위해 모든 테스트를 작성하는것보다, 보다 근본적으로 이 테스트들이 왜 필요한지를 고민해보시면 좋을 것 같아요. 관련해서 수형님이 좋은 코멘트를 남겨주신게 있어서 링크 남겨드립니다 :)
- https://github.com/CodeSoom/week7-assignment-1/pull/20/files#r518788581

2020-11-06 16:25 UTC, Kihyun92 commented on src/App.test.jsx
> +    });
각 test마다 처리하기보다 상위에서 처리해주면 어떨까요?

2020-11-06 16:25 UTC, Kihyun92 commented on src/Reviews.test.jsx
> +    const { container } = render(<Reviews reviews={[]} />);
`render(<Reviews reviews={[]} />` 부분이 중복되어 사용되는 것 같은데, 추상화해도 좋을 것 같네요~

2020-11-06 16:25 UTC, Kihyun92 commented on src/reducer.test.js
> +      },
loginFields 객체가 email이나 password 정보만 바뀌어서 재사용 되고 있는 것 같아요. 상위에 default value로 빈 값을 가지게 선언하고, 사용하는 곳에서 [전개구문](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax)을 사용해서 바뀌는 값만 넣어주는건 어떨까요?

2020-11-07 08:46 UTC, JamieShin0201 commented
안녕하세요 ㅎㅎㅎ

1. 리뷰받은 내용 살펴보고 전반적으로 수정하였습니다.

2. actions.js에 loadInitialData에서 지역, 카테고리 정보를 같이 가져오도록 수정하였습니다.
Promise.All을 사용해서 구현했었는데.. 테스트를 어떻게 작성해야할지 계속 찾아보다가 방법을 못 찾아서, 일단 async await 방식으로 수정하여 구현하였습니다.

3. actions.js에서 login() 함수를 통해 accessToken을 가져오지 못하면 saveItem()을 하지 못하게 코드를 수정하고 싶은데 테스트 작성을 어떻게 하면 좋을지 고민중입니다. 계속 생각해보겠습니다. 

4. 아직 남겨주신 storage 관련부분 읽어보지 못했는데 읽어보겠습니다.!!

감사합니다^__^

2020-11-07 18:53 UTC, Kihyun92 requested changes
점점 마무리가 되어가는 것 같네요~ 👍 
loadInitialData에서 Promise All을 사용해서 구현하려는 목적이 뭘까요? 제 생각에는 지금처럼 async/await만으로도 괜찮은 것 같아서요~

그리고 actions.js에서 fetchAccessToken을 통해 내려오는 응답값을 통해서 saveItem을 수행하지 못하도록 하는 처리를 할 수 있을 것 같아요. 
- https://ko.javascript.info/fetch

2020-11-07 18:53 UTC, Kihyun92 commented on src/App.test.jsx
> +  let accessToken = '';
let을 사용하지 않고 처리할 순 없을까요?

2020-11-07 18:53 UTC, Kihyun92 commented on src/Reviews.test.jsx
> +  function renderReviews(reviews) {
의미없는 빈배열을 넘기기 보단, 이곳에서 빈 배열을 default parameter로 지정해줘도 좋을 것 같네요~

2020-11-08 09:56 UTC, JamieShin0201 commented
안녕하세요 ㅎ.ㅎ

1. loadInitialData에서 promiseAll을 쓰려고 했던 이유는 
fetchRegions, fetchCategories 이 두 함수가 서로 의존적이지 않기에.. 빠르게 화면에 보이면 좋겠다고 생각해서 써보았습니다!

2. let을 쓰지않고 처리하는 법은 더 생각해봐야 할 것 같습니다!ㅠㅠ

감사합니다 ^_^

2020-11-08 15:14 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~ 👍
강의 풀이 영상 보시면서 과제 의도를 곱씹어 보시면 좋을 것 같아요 :)

이번 과제 Approve 하겠습니다~ 회고 작성 부탁드립니다~

2020-11-09 15:24 UTC, merged