🎨 레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기 ( 진행중..)
CodeSoom/week7-assignment-1 pull request #34
Opened 2020-11-05 11:58 UTC by Knoa0405

레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기 ( 진행중..)
아샬님 영상내용 따라가는 중입니다! 추가 PR 보내겠습니다~

2020-11-05 15:43 UTC, Kihyun92 commented
강의를 보시면서 내용들 잘 흡수해보시면 좋겠습니다 👍

2020-11-06 10:04 UTC, Knoa0405 commented
아샬님 영상은 다 따라 해봤고 오늘 새로 해서 처음부터 해보겠습니다~!

2020-11-07 18:01 UTC, Knoa0405 commented
## 벼락치기로 구현끝냈습니다...!

다음주는 일찍일찍 해야겠네요ㅠ
양이 많아 죄송합니다!
한번이지만 리뷰 빡시게 부탁드립니다~! 내일 최종 수정하겠습니다ㅠ

2020-11-08 07:54 UTC, Kihyun92 requested changes
리뷰가 늦었네요 😅

급하게 하셨는데 TDD를 잘 챙기면서 해주신 것 같아요 :)

전반적으로 잘 해주셨지만, 중복 코드 관련된 처리만 더 잘 이루어지면 좋을 것 같아요~

2020-11-08 07:54 UTC, Kihyun92 commented on src/LoginFormContainer.test.jsx
> +        );
보다 상위에서 추상화하여 할당해주는건 어떨까요?

2020-11-08 07:54 UTC, Kihyun92 commented on src/LoginPage.test.jsx
> +    );
중복 코드 제거 및 확장성을 고려했을때 마찬가지로 상위에서 추상화 해주면 좋겠네요~

2020-11-08 07:54 UTC, Kihyun92 commented on src/TextField.test.jsx
> +    const handleChange = jest.fn();
renderTextField 함수 밖에서 선언해주면 어떨까요? 아래 코드에도 테스트 안에서 따로 선언해주고 있는 것 같기도 하구요~

2020-11-08 14:58 UTC, Knoa0405 commented
## 피드 포워드를 많이 못받아 아쉬웠던 7주차입니다!ㅠ

반성하고 다음주는 첫 PR을 월요일로 잡겠습니다~!

회고록 작성 마쳤습니다~!
https://www.notion.so/7-e2d007f3689141a5865f05ea0d66b320

2020-11-08 15:08 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~ 저도 피드백을 많이 못드린 것 같아서 아쉽네요,, 🙏

강의 풀이 영상 보시면서 과제 의도를 곱씹어 보시면 좋을 것 같아요 :)

이번 과제 Approve 하겠습니다~

2020-11-09 15:25 UTC, merged